api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: 6379
      transport: tcp
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: redis-password
        value: '{{ securedParameter "basketcache_password" }}'
  template:
    volumes:
      - name: basketcache-aspireshopapphosta57d47ee87basketcachedata
        storageType: AzureFile
        storageName: {{ .Env.SERVICE_BASKETCACHE_VOLUME_ASPIRESHOPAPPHOSTA57D47EE87BASKETCACHEDATA_NAME }} 
    containers:
      - image: {{ .Image }}
        name: basketcache
        args:
          - -c
          - redis-server --requirepass $REDIS_PASSWORD --save 60 1
        command: [/bin/sh]
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: REDIS_PASSWORD
            secretRef: redis-password
        volumeMounts:
          - volumeName: basketcache-aspireshopapphosta57d47ee87basketcachedata
            mountPath: /data
    scale:
      minReplicas: 1
tags:
  azd-service-name: basketcache
  aspire-resource-name: basketcache
